apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jenkins-secret
type: Opaque
data:
  jenkins-admin-user: {{ .Values.admin.user | b64enc | quote }}
  jenkins-admin-password: {{ .Values.admin.password | b64enc | quote }}
